version: '3.7'

services:
  mysql:
    image: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
        - mynetwork
    deploy:
      replicas: 1 

  service-nodejs:
    image: backend
    ports:
      - "5050:3000"
    networks:
      - mynetwork
    deploy:
      replicas: 1 

  service-soap:
    image: soap
    ports:
      - "5555:5555"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  service-cliente   :
    image: frontend
    ports:
      - "8080:80"
    networks:
      - mynetwork
    deploy:
      replicas: 4 
  
  

networks:
  mynetwork:
